version: "3.9"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=authentication'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
